name: Build React Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Local Action with Input
        uses: Prajwal-Neu/teams-notifcation-v3@main
        with:
          milliseconds: 1000
