name: Build React Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Local Action with Input
        uses: ./.github/actions/my-action
        with:
          milliseconds: 1000
